/**
 * The adapter layer's two promises.
 *
 * One: an adapter is a function of canonical *frontmatter*, so editing a skill
 * body cannot change a byte of it. That is what makes generated files safe to
 * commit and verify.
 *
 * Two: Pathfinder writes a file only when the file says Pathfinder wrote it.
 * The name is never enough. Most of what follows is that rule, tested from
 * every side, because the one thing this tool must never do is replace a
 * skill someone wrote themselves.
 */

import { strict as assert } from "node:assert";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";

import {
  ADAPTER_STATE,
  MARKER_VERSION,
  adapterPath,
  canonicalPath,
  classifyAdapter,
  isPathfinderAdapter,
  parseSkillFrontmatter,
  readMarker,
  readSkillMetadata,
  render,
} from "../src/harnesses/adapter.mjs";
import {
  HARNESSES,
  HARNESS_IDS,
  detectedHarnesses,
  findHarness,
  harnessNamed,
} from "../src/harnesses/index.mjs";
import { findKitRoot } from "../src/kit.mjs";

const CLAUDE_CODE = findHarness("claude-code");
const CODEX = findHarness("codex");

/** A canonical skill file, assembled so a test can vary one part of it. */
function skillFile({
  name = "debug-issue",
  description = "Diagnose an observed software failure.",
  argumentHint = null,
  body = "# Debug Issue\n\n1. Reproduce the failure.\n",
} = {}) {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    ...(argumentHint ? [`argument-hint: ${argumentHint}`] : []),
    "---",
    "",
    body,
  ].join("\n");
}

describe("render — the bytes", () => {
  it("renders the representative adapter exactly", () => {
    const output = render(CLAUDE_CODE, {
      name: "debug-issue",
      description:
        "Diagnose an observed software failure systematically, identify the root cause with evidence, apply the smallest justified fix, and verify the failure is resolved without introducing regressions.",
    });

    assert.equal(
      output,
      `---
name: debug-issue
description: Diagnose an observed software failure systematically, identify the root cause with evidence, apply the smallest justified fix, and verify the failure is resolved without introducing regressions.
---

<!-- pathfinder:adapter v1 source=skills/debug-issue/SKILL.md -->
<!-- Generated by create-pathfinder. Do not edit; re-run \`npx create-pathfinder\`. -->

Read \`skills/debug-issue/SKILL.md\` in this repository and follow it exactly.

That file is the canonical, tool-neutral definition of this skill. This file
exists only so this tool can discover it, and contains no behavior of its own.

If \`skills/debug-issue/SKILL.md\` does not exist, stop and tell the user the
Pathfinder kit is not installed in this repository. Do not improvise the skill.
`,
    );
  });

  it("is deterministic — same input, same bytes, every call", () => {
    const metadata = { name: "reflect", description: "Review completed work." };
    const first = render(CLAUDE_CODE, metadata);

    for (let i = 0; i < 5; i += 1) assert.equal(render(CLAUDE_CODE, metadata), first);
  });

  it("writes LF endings and exactly one trailing newline", () => {
    const output = render(CLAUDE_CODE, { name: "handoff", description: "Preserve state." });

    assert.equal(output.includes("\r"), false);
    assert.equal(output.endsWith("\n"), true);
    assert.equal(output.endsWith("\n\n"), false);
  });

  it("names the canonical path, and only the canonical path", () => {
    const output = render(CLAUDE_CODE, { name: "to-specs", description: "Generate specs." });

    assert.equal(canonicalPath("to-specs"), "skills/to-specs/SKILL.md");
    assert.equal(output.match(/skills\/to-specs\/SKILL\.md/g).length, 3);
    assert.equal(output.includes(".claude"), false);
  });

  it("carries the marker in the format this build owns", () => {
    const output = render(CLAUDE_CODE, { name: "reflect", description: "Review work." });

    assert.deepEqual(readMarker(output), {
      version: MARKER_VERSION,
      source: "skills/reflect/SKILL.md",
    });
    assert.equal(isPathfinderAdapter(output), true);
  });

  it("refuses a skill without the metadata an adapter is made of", () => {
    assert.throws(() => render(CLAUDE_CODE, { description: "No name." }), /has no name/);
    assert.throws(() => render(CLAUDE_CODE, { name: "reflect" }), /`reflect` has no description/);
    assert.throws(() => render(null, { name: "reflect", description: "x" }), /harness is required/);
  });

  it("refuses a name that would escape the path it describes", () => {
    for (const name of ["../evil", "a/b", ".hidden", "x..y"]) {
      assert.throws(
        () => render(CLAUDE_CODE, { name, description: "x" }),
        /not usable as a path segment/,
        name,
      );
    }
  });
});

describe("render — metadata is carried, never rewritten", () => {
  it("reproduces a very long description verbatim", () => {
    const description = `Do the thing ${"and then some more of it ".repeat(20)}exhaustively.`;
    const output = render(CLAUDE_CODE, { name: "reflect", description });

    assert.equal(output.includes(`description: ${description}\n`), true);
    assert.equal(
      output.split("\n").some((line) => line.startsWith("description:") && line.endsWith("exhaustively.")),
      true,
    );
  });

  it("keeps a colon in a description", () => {
    const description = "Review work: extract lessons, then improve the workflow.";
    const output = render(CLAUDE_CODE, { name: "reflect", description });

    assert.equal(output.includes(`description: ${description}`), true);
  });

  it("includes argument-hint only when the canonical skill has one", () => {
    const withHint = render(CLAUDE_CODE, {
      name: "challenge-me",
      description: "Create a transfer exercise.",
      argumentHint: "design|debug|refactor|implement",
    });
    const without = render(CLAUDE_CODE, {
      name: "challenge-me",
      description: "Create a transfer exercise.",
    });

    assert.equal(withHint.includes("argument-hint: design|debug|refactor|implement\n"), true);
    assert.equal(without.includes("argument-hint"), false);
    assert.match(withHint, /description: .*\nargument-hint: .*\n---\n/);
  });

  it("adds no metadata the harness contract does not require", () => {
    const frontmatter = render(CLAUDE_CODE, {
      name: "reflect",
      description: "Review work.",
      argumentHint: "weekly",
    }).split("---\n")[1];

    assert.deepEqual(
      frontmatter.trimEnd().split("\n").map((line) => line.split(":")[0]),
      ["name", "description", "argument-hint"],
    );
  });
});

describe("render — body-independence", () => {
  it("produces identical bytes when only the canonical body changes", () => {
    const one = readSkill(skillFile({ body: "# One\n\nDo the first thing.\n" }));
    const two = readSkill(skillFile({ body: "# Two\n\nEntirely rewritten instructions.\n" }));

    assert.equal(render(CLAUDE_CODE, one), render(CLAUDE_CODE, two));
  });

  it("changes bytes when a represented metadata field changes", () => {
    const base = readSkill(skillFile());
    const reworded = readSkill(skillFile({ description: "Diagnose a failure, then fix it." }));
    const hinted = readSkill(skillFile({ argumentHint: "fast|thorough" }));

    assert.notEqual(render(CLAUDE_CODE, base), render(CLAUDE_CODE, reworded));
    assert.notEqual(render(CLAUDE_CODE, base), render(CLAUDE_CODE, hinted));
  });

  it("copies no line of the canonical body into the adapter", () => {
    const body = "Stop after 2-3 grounded failed approaches and explain the blocker.";
    const output = render(CLAUDE_CODE, readSkill(skillFile({ body })));

    assert.equal(output.includes(body), false);
  });
});

describe("parseSkillFrontmatter", () => {
  it("extracts the three fields an adapter is made of", () => {
    assert.deepEqual(parseSkillFrontmatter(skillFile({ argumentHint: "weekly" })), {
      name: "debug-issue",
      description: "Diagnose an observed software failure.",
      argumentHint: "weekly",
    });
  });

  it("reports a missing argument-hint as null rather than an empty string", () => {
    assert.equal(parseSkillFrontmatter(skillFile()).argumentHint, null);
  });

  it("keeps a colon in a value instead of splitting on it", () => {
    const description = "Review work: extract lessons.";

    assert.equal(parseSkillFrontmatter(skillFile({ description })).description, description);
  });

  it("reads a file whose frontmatter uses CRLF", () => {
    const parsed = parseSkillFrontmatter(skillFile().replace(/\n/g, "\r\n"));

    assert.equal(parsed.name, "debug-issue");
    assert.equal(parsed.description.includes("\r"), false);
  });

  it("fails clearly, naming the file, when required metadata is missing", () => {
    const noDescription = "---\nname: reflect\n---\n\nBody.\n";
    const noName = "---\ndescription: Review work.\n---\n\nBody.\n";

    assert.throws(
      () => parseSkillFrontmatter(noDescription, { source: "skills/reflect/SKILL.md" }),
      /skills\/reflect\/SKILL\.md: frontmatter `description` is missing or empty/,
    );
    assert.throws(() => parseSkillFrontmatter(noName), /`name` is missing or empty/);
    assert.throws(
      () => parseSkillFrontmatter("---\nname: reflect\ndescription:\n---\n"),
      /`description` is missing or empty/,
    );
  });

  it("fails clearly on a malformed block", () => {
    assert.throws(() => parseSkillFrontmatter("\n---\nname: x\n---\n"), /line 1 must be exactly/);
    assert.throws(() => parseSkillFrontmatter("---\nname: x\n----\n"), /no closing `---`/);
    assert.throws(
      () => parseSkillFrontmatter("---\nname: x\ndescription: y\n- a list\n---\n"),
      /is not a `key: value` pair/,
    );
  });
});

describe("readMarker — what proves ownership", () => {
  it("finds the marker this build writes", () => {
    const line = "<!-- pathfinder:adapter v1 source=skills/reflect/SKILL.md -->";

    assert.deepEqual(readMarker(`---\nname: reflect\n---\n\n${line}\n\nRead it.\n`), {
      version: 1,
      source: "skills/reflect/SKILL.md",
    });
  });

  it("accepts a marker with no source, and reports the version it saw", () => {
    assert.deepEqual(readMarker("<!-- pathfinder:adapter v1 -->"), { version: 1, source: null });
    assert.deepEqual(readMarker("<!-- pathfinder:adapter v2 -->"), { version: 2, source: null });
  });

  it("does not recognize a marker this build does not own", () => {
    assert.equal(isPathfinderAdapter("<!-- pathfinder:adapter v2 -->"), false);
    assert.equal(isPathfinderAdapter("<!-- pathfinder:adapter v11 -->"), false);
  });

  it("does not recognize a malformed or impostor marker", () => {
    for (const line of [
      "<!-- pathfinder:adapter -->",
      "<!-- pathfinder:adapter v -->",
      "<!-- pathfinder-adapter v1 -->",
      "<!-- pathfinder:adapters v1 -->",
      "pathfinder:adapter v1",
      "Mentions <!-- pathfinder:adapter v1 --> mid-sentence.",
      "",
    ]) {
      assert.equal(readMarker(line), null, line);
      assert.equal(isPathfinderAdapter(line), false, line);
    }

    assert.equal(readMarker(null), null);
    assert.equal(readMarker(undefined), null);
  });
});

describe("classifyAdapter — who owns this path", () => {
  const name = "debug-issue";
  const expected = render(CLAUDE_CODE, { name, description: "Diagnose a failure." });

  it("absent → generate", () => {
    const result = classifyAdapter({ name, isCanonicalSkill: true, existing: null, expected });

    assert.equal(result.state, ADAPTER_STATE.ABSENT);
    assert.equal(result.owned, true);
    assert.equal(result.forceReplaceable, false);
  });

  it("marked and identical → up to date", () => {
    const result = classifyAdapter({
      name,
      isCanonicalSkill: true,
      existing: expected,
      expected,
    });

    assert.equal(result.state, ADAPTER_STATE.CURRENT);
    assert.equal(result.owned, true);
  });

  it("marked and different → regenerate, no flag needed", () => {
    const handEdited = expected.replace("Read `skills", "Ignore that and read `skills");
    const result = classifyAdapter({
      name,
      isCanonicalSkill: true,
      existing: handEdited,
      expected,
    });

    assert.equal(result.state, ADAPTER_STATE.STALE);
    assert.equal(result.owned, true);
    assert.equal(result.forceReplaceable, false);
  });

  it("unmarked at an adapter path → the user's file, a conflict, never owned", () => {
    const mine = "---\nname: debug-issue\n---\n\nMy own take on debugging.\n";
    const result = classifyAdapter({ name, isCanonicalSkill: true, existing: mine, expected });

    assert.equal(result.state, ADAPTER_STATE.CONFLICT);
    assert.equal(result.owned, false);
    assert.equal(result.forceReplaceable, true);
  });

  it("a marker version this build does not own is a conflict, not a silent rewrite", () => {
    const future = expected.replace("v1 source=", "v2 source=");
    const result = classifyAdapter({ name, isCanonicalSkill: true, existing: future, expected });

    assert.equal(result.state, ADAPTER_STATE.CONFLICT);
    assert.equal(result.owned, false);
    assert.deepEqual(result.marker, { version: 2, source: "skills/debug-issue/SKILL.md" });
  });

  it("a name that matches no canonical skill is never touched", () => {
    const result = classifyAdapter({
      name: "my-own-skill",
      isCanonicalSkill: false,
      existing: "---\nname: my-own-skill\n---\n\nMine.\n",
    });

    assert.equal(result.state, ADAPTER_STATE.UNMANAGED);
    assert.equal(result.owned, false);
    assert.equal(result.forceReplaceable, false);
  });

  it("our marker on a skill this version no longer ships is an orphan, reported and kept", () => {
    const result = classifyAdapter({
      name: "retired-skill",
      isCanonicalSkill: false,
      existing: render(CLAUDE_CODE, { name: "retired-skill", description: "Gone." }),
    });

    assert.equal(result.state, ADAPTER_STATE.ORPHAN);
    assert.equal(result.owned, false);
    assert.equal(result.forceReplaceable, false);
  });

  it("classifies a name match with no marker the same way whatever the contents", () => {
    for (const existing of ["", "Anything at all.\n", "---\nname: debug-issue\n---\n"]) {
      assert.equal(
        classifyAdapter({ name, isCanonicalSkill: true, existing, expected }).state,
        ADAPTER_STATE.CONFLICT,
        JSON.stringify(existing),
      );
    }
  });
});

describe("the registry", () => {
  it("registers Claude Code and Codex, and nothing else", () => {
    assert.deepEqual(HARNESS_IDS, ["claude-code", "codex"]);

    assert.equal(CLAUDE_CODE.label, "Claude Code");
    assert.equal(CLAUDE_CODE.skillsDir, ".claude/skills");
    assert.equal(CLAUDE_CODE.invocation("debug-issue"), "/debug-issue");
    assert.equal(adapterPath(CLAUDE_CODE, "debug-issue"), ".claude/skills/debug-issue/SKILL.md");

    assert.equal(CODEX.label, "Codex");
    assert.equal(CODEX.skillsDir, ".agents/skills");
    assert.equal(CODEX.invocation("debug-issue"), "$debug-issue");
    assert.equal(adapterPath(CODEX, "debug-issue"), ".agents/skills/debug-issue/SKILL.md");
  });

  // The claim Feature 12 exists to test. If a harness ever needs more than a
  // path, this assertion is where that finding surfaces first.
  it("distinguishes its two harnesses by nothing but their directory", () => {
    const metadata = { name: "reflect", description: "Review completed work." };
    assert.equal(render(CODEX, metadata), render(CLAUDE_CODE, metadata));

    for (const name of ["handoff", "to-specs", "quiz-me"]) {
      assert.equal(
        adapterPath(CODEX, name),
        adapterPath(CLAUDE_CODE, name).replace(".claude/skills", ".agents/skills"),
      );
    }
  });

  it("returns null for an unknown id rather than guessing", () => {
    assert.equal(findHarness("cursor"), null);
    assert.equal(findHarness("agents"), null);
    assert.equal(findHarness(undefined), null);
  });

  it("reads detection by id instead of probing again", () => {
    const both = {
      tools: [
        { id: "claude-code", label: "Claude Code", detected: true },
        { id: "codex", label: "Codex", detected: true },
      ],
    };
    const codexOnly = {
      tools: [
        { id: "claude-code", label: "Claude Code", detected: false },
        { id: "codex", label: "Codex", detected: true },
      ],
    };
    const neither = {
      tools: [
        { id: "claude-code", label: "Claude Code", detected: false },
        { id: "codex", label: "Codex", detected: false },
      ],
    };

    assert.deepEqual(detectedHarnesses(both), [CLAUDE_CODE, CODEX]);
    assert.deepEqual(detectedHarnesses(codexOnly), [CODEX]);
    assert.deepEqual(detectedHarnesses(neither), []);
  });

  it("treats impoverished findings as nothing detected, never as an error", () => {
    for (const findings of [{}, { tools: [] }, undefined, { tools: [{ id: "vscode", detected: true }] }]) {
      assert.deepEqual(detectedHarnesses(findings), []);
    }
  });

  it("recognizes the names a supported harness actually goes by", () => {
    for (const typed of ["claude-code", "Claude Code", "claude code", "CLAUDE", "claude"]) {
      assert.equal(harnessNamed(typed), CLAUDE_CODE, typed);
    }
    for (const typed of ["codex", "Codex", " CODEX "]) {
      assert.equal(harnessNamed(typed), CODEX, typed);
    }
  });

  // Exact against those names, and nothing looser. A prefix match would claim
  // "code" for Codex, and refusing to record a name is only defensible when
  // the alternative really is a duplicate.
  it("claims nothing it is only nearly called", () => {
    for (const typed of ["code", "cod", "claude-code-cli", "vs code", "cursor", "", null]) {
      assert.equal(harnessNamed(typed), null, String(typed));
    }
  });

  it("is frozen, so nothing can register a harness at runtime", () => {
    assert.throws(() => HARNESSES.push({ id: "rogue" }), TypeError);
  });
});

describe("against the real kit", () => {
  const kitRoot = findKitRoot();
  const skillsRoot = kitRoot === null ? null : join(kitRoot, "skills");
  const names =
    skillsRoot === null
      ? []
      : readdirSync(skillsRoot, { withFileTypes: true })
          .filter((entry) => entry.isDirectory())
          .map((entry) => entry.name)
          .sort();

  it("finds the canonical skills", () => {
    assert.notEqual(kitRoot, null);
    assert.equal(names.length >= 20, true);
  });

  it("renders a self-identifying, body-free adapter for every canonical skill", () => {
    for (const name of names) {
      const path = join(skillsRoot, name, "SKILL.md");
      const metadata = readSkillMetadata(path, { source: `skills/${name}/SKILL.md` });
      const output = render(CLAUDE_CODE, metadata);

      assert.equal(metadata.name, name, name);
      assert.equal(isPathfinderAdapter(output), true, name);
      assert.equal(output.includes("\r"), false, name);
      assert.equal(output.includes(`description: ${metadata.description}\n`), true, name);

      // Nothing from the canonical body may appear in the adapter. Blank and
      // very short lines are skipped: `---` and an empty line are structure,
      // not behavior, and both legitimately appear on each side.
      const body = readFileSync(path, "utf8").split("\n---\n").slice(1).join("\n---\n");
      for (const line of body.split("\n")) {
        const trimmed = line.trim();
        if (trimmed.length < 12) continue;
        assert.equal(output.includes(trimmed), false, `${name}: ${trimmed}`);
      }
    }
  });

  it("gives exactly six skills an argument-hint, and copies each verbatim", () => {
    const hinted = names
      .map((name) => [name, readSkillMetadata(join(skillsRoot, name, "SKILL.md"))])
      .filter(([, metadata]) => metadata.argumentHint !== null);

    assert.deepEqual(
      hinted.map(([name]) => name),
      ["challenge-me", "feature", "learning-review", "quiz-me", "role", "teach-architecture"],
    );

    for (const [, metadata] of hinted) {
      assert.equal(
        render(CLAUDE_CODE, metadata).includes(`argument-hint: ${metadata.argumentHint}\n`),
        true,
      );
    }
  });
});

/** Parse a canonical file the way the installer will. */
function readSkill(text) {
  return parseSkillFrontmatter(text);
}
