/**
 * The warning hierarchy, and the rule that keeps diagnostics usable.
 *
 * The re-run screen is what this chunk exists for: a conflict, an orphan, and
 * thirty-six skipped files used to arrive as prose at one indent level, so
 * nothing about the shape of the output said whether anything needed you.
 *
 * Two properties are asserted, and neither is about colour bytes:
 *
 * - **Severity is carried three ways.** Colour, a glyph, and a leading category
 *   word. The `NO_COLOR` rendering must convey exactly the same hierarchy as
 *   the decorated one, so every assertion here that matters is made twice.
 * - **Payload is not decorated.** A path in a skipped, conflict, or orphan list
 *   is printed plain and pastes into a GitHub issue unedited.
 */

import { strict as assert } from "node:assert";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, describe, it } from "node:test";

import { run } from "../src/cli.mjs";
import { MARKER_TOKEN, MARKER_VERSION } from "../src/harnesses/adapter.mjs";

const temporaryRoots = [];

after(() => {
  for (const root of temporaryRoots) rmSync(root, { recursive: true, force: true });
});

function makeRepository() {
  const root = mkdtempSync(join(tmpdir(), "pathfinder-warn-"));
  temporaryRoots.push(root);
  mkdirSync(join(root, ".git"));
  return root;
}

async function install(cwd, environment = {}) {
  let out = "";
  let err = "";
  const code = await run(["--yes", "--agents", "claude-code"], {
    cwd,
    out: (text) => (out += text),
    err: (text) => (err += text),
    env: { LANG: "en_US.UTF-8" },
    platform: "linux",
    stdoutIsTTY: true,
    ...environment,
  });
  return { code, out, err };
}

const decorated = {};
const colourless = { env: { LANG: "en_US.UTF-8", NO_COLOR: "1" } };

/**
 * A repository that has been installed into once, then damaged in the two ways
 * a real re-run gets damaged: somebody's own file where an adapter goes, and an
 * adapter of ours pointing at a skill that no longer exists.
 */
async function reRunScenario() {
  const cwd = makeRepository();
  await install(cwd);

  const conflict = join(cwd, ".claude", "skills", "prototype", "SKILL.md");
  writeFileSync(conflict, "my own notes, not generated by Pathfinder\n", "utf8");

  const orphanDirectory = join(cwd, ".claude", "skills", "retired-experiment");
  mkdirSync(orphanDirectory, { recursive: true });
  writeFileSync(
    join(orphanDirectory, "SKILL.md"),
    `<!-- ${MARKER_TOKEN} v${MARKER_VERSION} source=skills/retired-experiment/SKILL.md -->\nRead it.\n`,
    "utf8",
  );

  return cwd;
}

/** Strip every SGR sequence, leaving what a NO_COLOR reader would have seen. */
function undecorated(text) {
  return text.replace(/\u001B\[[0-9;]*m/g, "");
}

describe("every warning category is named, glyphed, and coloured", () => {
  it("marks skipped files, a conflict, and an orphan as warnings", async () => {
    const cwd = await reRunScenario();
    const { out } = await install(cwd);

    // The category word — the carrier that survives everything.
    assert.match(out, /Skipped/, "no Skipped category");
    assert.match(out, /Conflict/, "no Conflict category");
    assert.match(out, /Orphan/, "no Orphan category");

    // Each one paired with the warn glyph, not merely tinted.
    for (const word of ["Skipped", "Conflict", "Orphan"]) {
      assert.match(undecorated(out), new RegExp(`▲ ${word}`), `${word} has no warn glyph`);
    }

    // And each one actually painted at warn, asserted through the level's
    // colour rather than by eye.
    assert.match(out, /\u001B\[33m▲ Skipped/, "Skipped is not painted warn");
    assert.match(out, /\u001B\[33m▲ Conflict/, "Conflict is not painted warn");
    assert.match(out, /\u001B\[33m▲ Orphan/, "Orphan is not painted warn");
  });

  it("conveys the identical hierarchy with colour off", async () => {
    const cwd = await reRunScenario();
    const { out: colour } = await install(cwd, decorated);

    const again = await reRunScenario();
    const { out: mono } = await install(again, colourless);

    assert.ok(!mono.includes("\u001B"), "an escape survived NO_COLOR");

    // The two renderings differ only in decoration. Normalising the temp paths
    // away, the words a reader relies on are the same words.
    for (const word of ["▲ Skipped", "▲ Conflict", "▲ Orphan", "✓", "·"]) {
      assert.ok(undecorated(colour).includes(word), `${word} missing from the decorated run`);
      assert.ok(mono.includes(word), `${word} missing from the colourless run`);
    }
  });

  it("keeps ok, info, warn, and bad distinct rather than collapsing them", async () => {
    const cwd = await reRunScenario();
    const { out } = await install(cwd);

    // Success is green, secondary information is dim or cyan, trouble is
    // yellow. If any two of these had been merged the run would still print,
    // which is exactly why it is asserted.
    assert.match(out, /\u001B\[32m✓/, "nothing rendered at ok");
    assert.match(out, /\u001B\[33m▲/, "nothing rendered at warn");
    assert.ok(/\u001B\[2m·|\u001B\[36m·/.test(out), "nothing rendered at info or dim");
  });

  it("does not cry wolf over a requested --force overwrite", async () => {
    // `--force` doing what it was asked is not a warning. Marking it as one is
    // how a tool teaches people to ignore its warnings.
    const cwd = makeRepository();
    await install(cwd);

    let out = "";
    await run(["--yes", "--force", "--agents", "claude-code"], {
      cwd,
      out: (text) => (out += text),
      err: () => {},
      env: { LANG: "en_US.UTF-8", NO_COLOR: "1" },
      platform: "linux",
      stdoutIsTTY: true,
    });

    assert.match(out, /overwritten \(--force\)/);
    assert.ok(
      /· \d+ files? overwritten \(--force\)/.test(out),
      "an overwrite was raised to warn",
    );
  });
});

describe("diagnostic paths stay copy-pasteable", () => {
  it("prints each path plain, one per line, undecorated", async () => {
    const cwd = await reRunScenario();
    const { out } = await install(cwd);

    const pathLine = out
      .split("\n")
      .find((line) => line.includes(".claude/skills/prototype/SKILL.md"));

    assert.ok(pathLine, "the conflicting path was never printed");
    assert.ok(!pathLine.includes("\u001B"), "the path line carries an escape sequence");
    assert.equal(pathLine.trim(), ".claude/skills/prototype/SKILL.md");
  });

  it("puts no gutter, glyph, or box character in front of a path", async () => {
    const cwd = await reRunScenario();
    const { out } = await install(cwd, colourless);

    for (const path of [
      ".claude/skills/prototype/SKILL.md",
      ".claude/skills/retired-experiment/SKILL.md",
    ]) {
      const line = out.split("\n").find((candidate) => candidate.includes(path));
      const prefix = line.slice(0, line.indexOf(path));

      assert.match(prefix, /^ *$/, `"${prefix}" decorates a diagnostic path`);
    }
  });

  it("never wraps or truncates a path, however long", async () => {
    const cwd = await reRunScenario();
    const { out } = await install(cwd, colourless);

    const skipped = out
      .split("\n")
      .filter((line) => /^ +(context|skills|templates)\//.test(line));

    assert.ok(skipped.length > 0, "no skipped paths were listed");
    for (const line of skipped) {
      assert.ok(!line.includes("…"), "a path was truncated");
      assert.ok(!line.includes("..."), "a path was truncated");
      assert.equal(line.trim().split(/\s+/).length, 1, `"${line}" holds more than a path`);
    }
  });

  it("pastes back as the exact relative paths, in order", async () => {
    // The property a user actually depends on: select the block, paste it into
    // an issue, and get paths a maintainer can act on with no hand-editing.
    const cwd = await reRunScenario();
    const { out } = await install(cwd, colourless);

    const start = out.indexOf("▲ Skipped");
    const end = out.indexOf("Nothing above was modified");
    const pasted = out
      .slice(start, end)
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("▲"));

    assert.ok(pasted.length >= 30, `expected the skipped list, got ${pasted.length} lines`);
    for (const line of pasted) {
      assert.match(line, /^[\w.@-]+(\/[\w.@-]+)*$/, `"${line}" is not a bare path`);
    }
  });
});

describe("the contract tier is untouched by any of this", () => {
  it("prints no glyph, colour, or category word when stdout is not a terminal", async () => {
    const cwd = await reRunScenario();

    let out = "";
    await run(["--yes", "--agents", "claude-code"], {
      cwd,
      out: (text) => (out += text),
      err: () => {},
      env: { LANG: "en_US.UTF-8" },
      platform: "linux",
      stdoutIsTTY: false,
    });

    assert.ok(!out.includes("\u001B"), "an escape reached a non-terminal");
    assert.ok(!out.includes("▲"), "a warn glyph reached a non-terminal");
    assert.ok(!out.includes("SUMMARY"), "the expressive heading reached a non-terminal");
    assert.match(out, /^Installed the Pathfinder kit into /);

    // The 1.4.1 phrasing, still exactly as scripts have always read it.
    assert.match(out, /files left untouched because they already exist:/);
  });
});
