/**
 * The copier.
 *
 * Split in two on purpose. `planInstall` decides what would happen and touches
 * nothing; `applyPlan` carries a plan out. That split is what makes --dry-run
 * honest — it runs the identical planning code the real install runs, rather
 * than a parallel description of it that can drift.
 *
 * Harness adapters get their own pair, `planAdapters` / `applyAdapterPlan`,
 * under the same discipline. They are kept apart from the kit copy because
 * they answer a different question — the kit copy asks "does this file exist
 * yet?", and an adapter asks "did Pathfinder write this file?" — and because
 * adapters are generated bytes rather than copied ones.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

import { COPY_LIST, isExcluded } from "./kit.mjs";
import {
  ADAPTER_STATE,
  adapterPath,
  classifyAdapter,
  isPathfinderAdapter,
  readCanonicalSkills,
  render,
} from "./harnesses/adapter.mjs";

/**
 * Decide the fate of every file in the kit. Reads only; writes nothing.
 *
 * Existing files are detected one file at a time rather than one top-level
 * entry at a time. A project that already has `context/` gets the files it is
 * missing and keeps the ones it wrote, instead of the whole directory being
 * declared present and skipped.
 *
 * @returns {{relativePath: string, source: string, destination: string,
 *            status: "write" | "skip" | "overwrite"}[]}
 */
export function planInstall(kitRoot, targetRoot, { force = false } = {}) {
  const plan = [];

  for (const entry of COPY_LIST) {
    for (const source of walkFiles(join(kitRoot, entry))) {
      const relativePath = relative(kitRoot, source).split(sep).join("/");
      const destination = join(targetRoot, relativePath);
      const exists = existsSync(destination);

      plan.push({
        relativePath,
        source,
        destination,
        status: !exists ? "write" : force ? "overwrite" : "skip",
      });
    }
  }

  return plan.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
}

/**
 * Carry out a plan.
 *
 * Failures are collected rather than thrown, so one unwritable path reports
 * itself alongside everything that did succeed instead of aborting the run
 * halfway with no summary. Entries marked `skip` are never opened.
 *
 * `onProgress` is called once per plan item, after that item has resolved, with
 * the item and whether it succeeded. It exists so a caller can report real
 * progress without this function knowing what a progress bar is — there is no
 * timer here, no rate, and no percentage, because a completion event is the
 * only thing this layer actually knows. Omit it and nothing changes: the
 * callback is the only difference between this and the version that had no
 * parameter at all.
 *
 * A failed write reports `ok: false` rather than being skipped silently. A
 * caller that counted only calls, and not outcomes, could otherwise render a
 * complete bar over a partly failed install.
 *
 * @returns {{written: number, skipped: number, overwritten: number,
 *            errors: {relativePath: string, message: string}[]}}
 */
export function applyPlan(plan, { dryRun = false, onProgress } = {}) {
  const result = { written: 0, skipped: 0, overwritten: 0, errors: [] };

  for (const item of plan) {
    if (item.status === "skip") {
      result.skipped += 1;
      onProgress?.({ item, ok: true });
      continue;
    }

    if (!dryRun) {
      try {
        mkdirSync(dirname(item.destination), { recursive: true });
        copyFileSync(item.source, item.destination);
      } catch (error) {
        result.errors.push({
          relativePath: item.relativePath,
          message: error.message,
        });
        onProgress?.({ item, ok: false });
        continue;
      }
    }

    if (item.status === "overwrite") result.overwritten += 1;
    else result.written += 1;
    onProgress?.({ item, ok: true });
  }

  return result;
}

/**
 * Decide the fate of every adapter path for the selected harnesses.
 *
 * The same plan/apply discipline the kit copy uses, and for the same reason:
 * `--dry-run` reports by running this exact function, not a description of it.
 * Reads only.
 *
 * The set of skills comes from the kit, so an adapter is planned for what this
 * version ships and nothing else. Anything already under the harness directory
 * that is not one of those names is looked at exactly once — to see whether it
 * carries our marker, which makes it an orphan worth reporting — and is never
 * written.
 *
 * @returns {{harness: object, name: string, relativePath: string, destination: string,
 *            state: string, action: "write"|"replace"|"up-to-date"|"conflict"|"orphan"|"unreadable",
 *            contents: string|null, message?: string}[]}
 */
export function planAdapters(harnesses, { kitRoot, targetRoot, force = false } = {}) {
  const skills = readCanonicalSkills(kitRoot);
  const canonicalNames = new Set(skills.map((skill) => skill.name));
  const plan = [];

  for (const harness of harnesses) {
    for (const skill of skills) {
      const relativePath = adapterPath(harness, skill.name);
      const destination = join(targetRoot, ...relativePath.split("/"));
      const contents = render(harness, skill);
      const existing = readAdapter(destination);

      if (existing.unreadable) {
        plan.push({
          harness,
          name: skill.name,
          relativePath,
          destination,
          state: ADAPTER_STATE.CONFLICT,
          action: "unreadable",
          contents: null,
          message: existing.message,
        });
        continue;
      }

      const classified = classifyAdapter({
        name: skill.name,
        isCanonicalSkill: true,
        existing: existing.content,
        expected: contents,
      });

      plan.push({
        harness,
        name: skill.name,
        relativePath,
        destination,
        state: classified.state,
        action: actionFor(classified.state, force),
        contents,
      });
    }

    for (const name of orphanNames(harness, targetRoot, canonicalNames)) {
      const relativePath = adapterPath(harness, name);
      plan.push({
        harness,
        name,
        relativePath,
        destination: join(targetRoot, ...relativePath.split("/")),
        state: ADAPTER_STATE.ORPHAN,
        action: "orphan",
        contents: null,
      });
    }
  }

  return plan;
}

/**
 * What a classification means for this run.
 *
 * `--force` reaches exactly one state. It authorizes replacing a file
 * Pathfinder does not own at a path it would otherwise generate — the same
 * category of decision as replacing a kit file the user has edited, which is
 * why it is the same flag rather than a second one.
 */
function actionFor(state, force) {
  switch (state) {
    case ADAPTER_STATE.ABSENT:
    case ADAPTER_STATE.STALE:
      return "write";
    case ADAPTER_STATE.CURRENT:
      return "up-to-date";
    case ADAPTER_STATE.CONFLICT:
      return force ? "replace" : "conflict";
    default:
      return "orphan";
  }
}

/**
 * Carry out an adapter plan.
 *
 * Failures are collected rather than thrown, exactly as the kit copy does, so
 * one unwritable path reports itself next to everything that did succeed.
 * Conflicts and orphans are outcomes, not errors: nothing went wrong, and the
 * files they name are the ones this tool successfully left alone.
 *
 * `onProgress` behaves exactly as it does in `applyPlan`, and for the same
 * reason: one call per plan item, after it resolves, carrying the item and
 * whether it succeeded. Conflicts, orphans, and up-to-date adapters all report
 * `ok: true` — nothing went wrong in any of those cases, and each one is an
 * enumerated unit of a plan the user is watching being carried out. Only an
 * unreadable file and a failed write report `ok: false`.
 *
 * @returns {{generated: number, replaced: number, unchanged: number,
 *            conflicts: string[], orphans: string[],
 *            errors: {relativePath: string, message: string}[]}}
 */
export function applyAdapterPlan(plan, { dryRun = false, onProgress } = {}) {
  const result = { generated: 0, replaced: 0, unchanged: 0, conflicts: [], orphans: [], errors: [] };

  for (const item of plan) {
    switch (item.action) {
      case "up-to-date":
        result.unchanged += 1;
        onProgress?.({ item, ok: true });
        continue;
      case "conflict":
        result.conflicts.push(item.relativePath);
        onProgress?.({ item, ok: true });
        continue;
      case "orphan":
        result.orphans.push(item.relativePath);
        onProgress?.({ item, ok: true });
        continue;
      case "unreadable":
        result.errors.push({ relativePath: item.relativePath, message: item.message });
        onProgress?.({ item, ok: false });
        continue;
      default:
        break;
    }

    if (!dryRun) {
      try {
        mkdirSync(dirname(item.destination), { recursive: true });
        writeFileSync(item.destination, item.contents, "utf8");
      } catch (error) {
        result.errors.push({ relativePath: item.relativePath, message: error.message });
        onProgress?.({ item, ok: false });
        continue;
      }
    }

    if (item.action === "replace") result.replaced += 1;
    else result.generated += 1;
    onProgress?.({ item, ok: true });
  }

  return result;
}

/**
 * Read a file that may not be there.
 *
 * A missing file and a missing directory are the same answer — nothing is
 * there — but an *unreadable* file is not. Treating a permissions error as
 * absence would classify someone's file as "generate here", which is the one
 * mistake this layer exists to prevent, so it becomes a reported error instead.
 */
function readAdapter(path) {
  try {
    return { content: readFileSync(path, "utf8"), unreadable: false };
  } catch (error) {
    if (error.code === "ENOENT" || error.code === "ENOTDIR") {
      return { content: null, unreadable: false };
    }
    return { content: null, unreadable: true, message: error.message };
  }
}

/**
 * Names under the harness directory that carry our marker but are not skills
 * this version ships.
 *
 * Reported, never deleted. Any failure to look — no directory, no permission —
 * is simply "no orphans", because this is a courtesy check and must not be able
 * to fail an install.
 */
function orphanNames(harness, targetRoot, canonicalNames) {
  const skillsDirectory = join(targetRoot, ...harness.skillsDir.split("/"));

  try {
    return readdirSync(skillsDirectory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && !canonicalNames.has(entry.name))
      .map((entry) => entry.name)
      .sort()
      .filter((name) => {
        const file = readAdapter(join(skillsDirectory, name, "SKILL.md"));
        return file.content !== null && isPathfinderAdapter(file.content);
      });
  } catch {
    return [];
  }
}

/** Every file under `path`, recursively, minus junk. A file yields itself. */
function* walkFiles(path) {
  const stats = statSync(path);

  if (!stats.isDirectory()) {
    yield path;
    return;
  }

  for (const child of readdirSync(path).sort()) {
    if (isExcluded(child)) continue;
    yield* walkFiles(join(path, child));
  }
}
